name: release

on:
  push:
    branches: [master, main]
    tags: [v*]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  go-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses: lrstanley/.github/.github/workflows/lang-go-release.yml@master
    secrets: inherit
    with:
      upload-artifacts: true
  docker-release:
    uses: lrstanley/.github/.github/workflows/docker-release.yml@master
    secrets: inherit
    with:
      dockerfile: .github/Dockerfile
